\set ON_ERROR_STOP on

ALTER SCHEMA app OWNER TO a07_app;
ALTER SCHEMA demo OWNER TO a07_app;
ALTER TABLE app.app_config OWNER TO a07_app;

GRANT CONNECT ON DATABASE a07_agent TO a07_app;
GRANT USAGE, CREATE ON SCHEMA app, demo TO a07_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA app, demo TO a07_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA app, demo TO a07_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA app, demo
    GRANT ALL PRIVILEGES ON TABLES TO a07_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA app, demo
    GRANT ALL PRIVILEGES ON SEQUENCES TO a07_app;
